# Generated by Django 2.2 on 2019-04-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsScrapy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='manufacturer',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='sn',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
