# Generated by Django 2.2 on 2019-04-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsScrapy', '0002_auto_20190423_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='sn',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
